server:
  port: 12000
spring:
  application:
    name: tensquare-config #指定服务名
  cloud:
    config:
      server:
        git:

          uri: https://github.com/remember0324/tensquare.git
  rabbitmq:
    host: 192.168.40.144
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh